name: Generate Code
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  generate-code:
    runs-on: ubuntu-latest
    steps:
      - name: ãƒªãƒã‚¸ãƒˆãƒªã®ãƒã‚§ãƒƒã‚¯ã‚¢ã‚¦ãƒˆ
        uses: actions/checkout@v2
      - name: typescriptã®ã‚³ãƒ¼ãƒ‰ç”Ÿæˆ
        run: make generate-docker-typescript
      - name: JDK 11ã®ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.ACTION_TOKEN }}
      - name: springã®ã‚³ãƒ¼ãƒ‰ç”Ÿæˆ
        run: make generate-docker-spring
      - name: jarãƒ•ã‚¡ã‚¤ãƒ«ç”Ÿæˆï¼ˆMavenã§ãƒ“ãƒ«ãƒ‰ï¼‰
        run: cd spring && mvn clean package
      - name: mavenãƒ‘ãƒƒã‚±ãƒ¼ã‚¸ã®ãƒ‡ãƒ—ãƒ­ã‚¤
        run: cd spring && mvn deploy
      - name: ç”Ÿæˆã‚³ãƒ¼ãƒ‰ã®ã‚³ãƒŸãƒƒãƒˆ
        run: |
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add .
            git commit -m "Generated code"
      - name: ç”Ÿæˆã‚³ãƒ¼ãƒ‰ã®ãƒ—ãƒƒã‚·ãƒ¥
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."