name: Generate Code
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  generate-code:
    runs-on: ubuntu-latest
    steps:
      - name: ãƒªãƒã‚¸ãƒˆãƒªã®ãƒã‚§ãƒƒã‚¯ã‚¢ã‚¦ãƒˆ
        uses: actions/checkout@v2
      - name: typescriptã®ã‚³ãƒ¼ãƒ‰ç”Ÿæˆ
        run: make generate-docker-typescript
      - name: springã®ã‚³ãƒ¼ãƒ‰ç”Ÿæˆ
        run: make generate-docker-spring
      - run: echo "ğŸ This job's status is ${{ job.status }}."